const countries = {
  al: "Albania",
  ad: "Andorra",
  am: "Armenia",
  at: "Austria",
  az: "Azerbaijan",
  by: "Belarus",
  be: "Belgium",
  ba: "Bosnia and Herzegovina",
  bg: "Bulgaria",
  hr: "Croatia",
  cy: "Cyprus",
  cz: "Czech Republic",
  dk: "Denmark",
  ee: "Estonia",
  fi: "Finland",
  fr: "France",
  ge: "Georgia",
  de: "Germany",
  gr: "Greece",
  hu: "Hungary",
  is: "Iceland",
  ie: "Ireland",
  it: "Italy",
  kz: "Kazakhstan",
  xk: "Kosovo",
  lv: "Latvia",
  li: "Liechtenstein",
  lt: "Lithuania",
  lu: "Luxembourg",
  mk: "North Macedonia",
  mt: "Malta",
  md: "Moldova",
  mc: "Monaco",
  me: "Montenegro",
  nl: "Netherlands",
  no: "Norway",
  pl: "Poland",
  pt: "Portugal",
  ro: "Romania",
  ru: "Russia",
  sm: "San Marino",
  rs: "Serbia",
  sk: "Slovakia",
  si: "Slovenia",
  es: "Spain",
  se: "Sweden",
  ch: "Switzerland",
  tr: "Turkey",
  ua: "Ukraine",
  gb: "United Kingdom",
  va: "Vatican City (Holy See)",
};

export default countries;
