const countries = {
  GER: { code2: "de", name: "Germany" },
  SCO: { code2: "gb-sct", name: "Scotland" },
  HUN: { code2: "hu", name: "Hungary" },
  SUI: { code2: "ch", name: "Switzerland" },
  ESP: { code2: "es", name: "Spain" },
  CRO: { code2: "hr", name: "Croatia" },
  ITA: { code2: "it", name: "Italy" },
  ALB: { code2: "al", name: "Albania" },
  SVN: { code2: "si", name: "Slovenia" },
  DEN: { code2: "dk", name: "Denmark" },
  SRB: { code2: "rs", name: "Serbia" },
  ENG: { code2: "gb-eng", name: "England" },
  POL: { code2: "pl", name: "Poland" },
  NED: { code2: "nl", name: "Netherlands" },
  AUT: { code2: "at", name: "Austria" },
  FRA: { code2: "fr", name: "France" },
  BEL: { code2: "be", name: "Belgium" },
  SVK: { code2: "sk", name: "Slovakia" },
  ROU: { code2: "ro", name: "Romania" },
  UKR: { code2: "ua", name: "Ukraine" },
  TUR: { code2: "tr", name: "Turkey" },
  GEO: { code2: "ge", name: "Georgia" },
  POR: { code2: "pt", name: "Portugal" },
  CZE: { code2: "cz", name: "Czech Republic" },
  SHU: { code2: "-", name: "Sheffield United" },
  NTG: { code2: "-", name: "Nottingham Forest" },
  MCI: { code2: "-", name: "Manchester City" },
  WLV: { code2: "-", name: "Wolverhampton" },
  BRH: { code2: "-", name: "Brighton" },
  AVA: { code2: "-", name: "Aston Villa" },
  CHE: { code2: "-", name: "Chelsea" },
  WHU: { code2: "-", name: "West Ham United" },
};

export default countries;
